#!/usr/bin/env bash

set -ex

OUTPUT_FOLDER=/data/2019-10-28/cooking_competition

tw-make challenge tw-cooking-recipe2+valid --seed 12876 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+valid --seed 20249 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+valid --seed 21976 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+go12+valid --seed 390 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+go9+valid --seed 2457 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+valid --seed 5042 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+valid --seed 11915 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+go6+valid --seed 19816 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+valid --seed 22618 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+go6+valid --seed 23342 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+go9+valid --seed 36125 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+go6+valid --seed 36932 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+go9+valid --seed 57690 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+valid --seed 2844 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+go12+valid --seed 23476 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+valid --seed 30446 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+go12+valid --seed 38553 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+valid --seed 46638 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+valid --seed 57379 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+valid --seed 14727 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+valid --seed 51430 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+valid --seed 135 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+go9+valid --seed 267 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+go6+valid --seed 9352 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+valid --seed 6881 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+go6+valid --seed 8160 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+open+go9+valid --seed 9534 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+open+go9+valid --seed 9991 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+go6+valid --seed 14766 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+go9+valid --seed 41337 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+go6+valid --seed 50049 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+go9+valid --seed 52004 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+go9+valid --seed 62033 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+valid --seed 2314 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+go12+valid --seed 4257 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+open+go12+valid --seed 8792 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+drop+valid --seed 10364 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+open+go6+valid --seed 11771 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+open+go6+valid --seed 12766 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+go6+valid --seed 14272 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+go6+valid --seed 18444 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+go9+valid --seed 22995 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+go12+valid --seed 23446 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+valid --seed 24232 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+go12+valid --seed 26520 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+go9+valid --seed 30781 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+open+go9+valid --seed 31204 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+open+go6+valid --seed 40996 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+drop+valid --seed 44551 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+go12+valid --seed 56946 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+drop+valid --seed 59208 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+drop+valid --seed 6809 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+go6+valid --seed 18069 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+go9+valid --seed 20436 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+valid --seed 21375 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+go12+valid --seed 34329 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+valid --seed 37805 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+go12+valid --seed 41612 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+open+go12+valid --seed 45615 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+open+go12+valid --seed 46093 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+go6+valid --seed 983 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+valid --seed 11743 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+valid --seed 17431 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+valid --seed 24818 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+valid --seed 24994 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+valid --seed 45542 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+valid --seed 45653 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+drop+valid --seed 48680 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+go12+valid --seed 51045 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+drop+valid --seed 51396 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+drop+go6+valid --seed 2086 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+open+go9+valid --seed 6020 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+go6+valid --seed 6967 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+go9+valid --seed 8846 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+open+go9+valid --seed 9339 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+go9+valid --seed 10159 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+drop+go9+valid --seed 12277 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+go9+valid --seed 13830 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+go9+valid --seed 16569 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+drop+go6+valid --seed 20144 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+go6+valid --seed 29808 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+open+go9+valid --seed 35193 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+go6+valid --seed 38595 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+drop+go9+valid --seed 39329 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+drop+go6+valid --seed 41027 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+open+go6+valid --seed 41442 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+open+go6+valid --seed 41488 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+drop+go9+valid --seed 51278 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+go9+valid --seed 54907 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+drop+valid --seed 2230 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+valid --seed 8810 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+go9+valid --seed 9869 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+drop+valid --seed 10145 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+open+go12+valid --seed 10469 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+open+go9+valid --seed 10993 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+go12+valid --seed 18187 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+drop+go12+valid --seed 24542 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+open+go9+valid --seed 25496 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+open+go6+valid --seed 25903 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+drop+valid --seed 29966 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+open+go6+valid --seed 33290 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+open+go12+valid --seed 36108 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+open+go6+valid --seed 45100 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+go12+valid --seed 48207 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+drop+valid --seed 49210 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+go12+valid --seed 51143 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+drop+go12+valid --seed 55340 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+go12+valid --seed 61342 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+go6+valid --seed 62479 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+drop+go12+valid --seed 63663 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+drop+valid --seed 8136 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+drop+valid --seed 9036 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+valid --seed 9267 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+go6+valid --seed 10578 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+drop+valid --seed 13511 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+valid --seed 16306 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+drop+valid --seed 16604 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+open+go12+valid --seed 17904 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+drop+go9+valid --seed 28756 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+go9+valid --seed 34577 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+go12+valid --seed 35245 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+valid --seed 36693 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+open+go12+valid --seed 47888 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+go6+valid --seed 53885 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+open+go12+valid --seed 55820 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+valid --seed 58120 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+valid --seed 59178 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+valid --seed 64317 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+drop+go6+valid --seed 64598 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+go9+valid --seed 455 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+go12+valid --seed 15899 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+valid --seed 21755 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+drop+valid --seed 23320 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+go12+valid --seed 24690 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+valid --seed 32020 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+drop+valid --seed 34056 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+drop+valid --seed 42975 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+drop+go12+valid --seed 51034 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+drop+valid --seed 57201 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+drop+go9+valid --seed 4657 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+open+go6+valid --seed 15221 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+open+go9+valid --seed 18660 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+open+go6+valid --seed 23993 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+open+drop+go9+valid --seed 24542 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+drop+go6+valid --seed 25538 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+drop+go9+valid --seed 25571 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+drop+go9+valid --seed 26673 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+drop+go9+valid --seed 31187 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+drop+go6+valid --seed 38501 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+go6+valid --seed 51592 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+open+go9+valid --seed 54171 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+open+drop+go6+valid --seed 58232 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+open+drop+go9+valid --seed 58955 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+drop+go6+valid --seed 60402 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+open+drop+go6+valid --seed 61395 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+drop+go6+valid --seed 61399 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+go12+valid --seed 2144 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+valid --seed 7523 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+drop+go12+valid --seed 10185 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+drop+go12+valid --seed 13255 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+drop+go9+valid --seed 16124 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+open+drop+go12+valid --seed 22345 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+open+go12+valid --seed 23685 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+open+go12+valid --seed 24205 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+go12+valid --seed 27383 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+drop+go6+valid --seed 31806 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+drop+go12+valid --seed 33375 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+drop+go12+valid --seed 39560 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+go9+valid --seed 44050 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+go6+valid --seed 47718 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+go9+valid --seed 52811 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+open+drop+go12+valid --seed 54935 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+go6+valid --seed 56149 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+drop+valid --seed 3930 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+go9+valid --seed 18320 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+drop+go12+valid --seed 19840 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+drop+valid --seed 20491 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+drop+go9+valid --seed 21557 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+valid --seed 23198 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+drop+go9+valid --seed 24671 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+drop+valid --seed 24993 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+drop+valid --seed 35326 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+drop+valid --seed 37384 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+valid --seed 41951 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+drop+go6+valid --seed 42537 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+drop+valid --seed 49869 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+go12+valid --seed 52739 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+go6+valid --seed 57350 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+drop+valid --seed 58359 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+drop+go6+valid --seed 63740 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+go12+valid --seed 17433 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+drop+go12+valid --seed 28164 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+drop+go12+valid --seed 41038 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+drop+valid --seed 41355 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+drop+valid --seed 41729 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+drop+go9+valid --seed 9093 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+go9+valid --seed 1778 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+drop+go6+valid --seed 7034 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+open+drop+go6+valid --seed 21065 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+open+drop+go6+valid --seed 33874 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+open+drop+go9+valid --seed 45438 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+drop+go6+valid --seed 46576 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+open+drop+go9+valid --seed 57710 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+drop+go12+valid --seed 2565 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+drop+go9+valid --seed 9679 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+open+drop+go12+valid --seed 13510 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+drop+go12+valid --seed 23529 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+drop+go9+valid --seed 33943 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+open+drop+go12+valid --seed 40971 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+drop+go9+valid --seed 41408 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+drop+go6+valid --seed 49703 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+go6+valid --seed 59609 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+drop+go6+valid --seed 21516 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+drop+valid --seed 23282 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+drop+go12+valid --seed 34956 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+drop+valid --seed 53376 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+drop+valid --seed 54988 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+go12+valid --seed 59459 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+drop+go12+valid --seed 43404 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+drop+go12+valid --seed 9956 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+drop+go9+valid --seed 12811 --output $OUTPUT_FOLDER/valid/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+drop+go6+valid --seed 15099 --output $OUTPUT_FOLDER/valid/ --silent -f
