#!/usr/bin/env bash

set -ex

OUTPUT_FOLDER=/data/2019-10-28/cooking_competition

tw-make challenge tw-cooking-recipe4+test --seed 1207 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+test --seed 21911 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+test --seed 39139 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+test --seed 47282 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+test --seed 59280 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+test --seed 6058 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+test --seed 256 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+test --seed 15440 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+go6+test --seed 19277 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+test --seed 22724 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+go9+test --seed 39094 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+cut+test --seed 50626 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+cut+test --seed 52687 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+test --seed 16003 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+test --seed 17983 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+cook+test --seed 22790 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+test --seed 31126 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+go12+test --seed 48258 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+cook+test --seed 50800 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+test --seed 38903 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+test --seed 40741 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+test --seed 43255 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+test --seed 52172 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+test --seed 52605 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+test --seed 65140 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+go6+test --seed 26319 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+go9+test --seed 50557 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+go12+test --seed 973 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+test --seed 2298 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+go6+test --seed 2483 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+go9+test --seed 5219 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+go12+test --seed 19752 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+drop+test --seed 24378 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+cut+drop+test --seed 26881 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+go6+test --seed 27208 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+open+go9+test --seed 27266 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+cut+drop+test --seed 27759 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+cook+cut+test --seed 28158 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+test --seed 42362 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+go9+test --seed 50445 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+open+go6+test --seed 56977 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+test --seed 57242 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+cook+cut+test --seed 59934 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+cut+drop+test --seed 60938 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+test --seed 62040 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+cut+drop+test --seed 64074 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+go12+test --seed 2996 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+drop+test --seed 5672 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+go12+test --seed 9683 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+go6+test --seed 14394 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+go6+test --seed 19623 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+go9+test --seed 21056 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+test --seed 24152 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+go9+test --seed 24948 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+test --seed 25885 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+test --seed 26604 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+go9+test --seed 29897 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+go9+test --seed 40486 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+test --seed 42005 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+test --seed 44264 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+go12+test --seed 45246 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+go6+test --seed 45501 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+go6+test --seed 55448 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+go9+test --seed 57101 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+open+go12+test --seed 58658 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+go9+test --seed 59123 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+go6+test --seed 59182 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+test --seed 59688 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+go6+test --seed 60409 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+open+go9+test --seed 68 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+test --seed 11310 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+open+test --seed 11774 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+test --seed 14365 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+drop+test --seed 14464 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+test --seed 17684 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+drop+test --seed 19787 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+go12+test --seed 20091 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+test --seed 22832 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+open+test --seed 23691 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+go12+test --seed 29636 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+test --seed 30403 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+drop+test --seed 30973 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+open+test --seed 34938 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+test --seed 34997 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+test --seed 36994 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+test --seed 37884 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+test --seed 44562 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+drop+test --seed 54218 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+go12+test --seed 56175 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+go12+test --seed 59104 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+test --seed 59401 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+open+test --seed 59602 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+drop+test --seed 64155 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+drop+test --seed 64906 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+drop+go12+test --seed 7 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+test --seed 842 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+go9+test --seed 4938 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+cook+cut+drop+test --seed 6855 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+cook+cut+drop+test --seed 7772 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+go9+test --seed 7994 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+drop+go12+test --seed 9118 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+go6+test --seed 13301 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+go9+test --seed 22539 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+go6+test --seed 27430 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+drop+go6+test --seed 34359 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+go9+test --seed 48017 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+drop+go9+test --seed 60926 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+go12+test --seed 505 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+go12+test --seed 947 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+go9+test --seed 1120 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+drop+go9+test --seed 2772 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+go12+test --seed 4278 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+go6+test --seed 4380 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+go6+test --seed 5329 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+go12+test --seed 5660 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+open+go12+test --seed 7268 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+test --seed 8258 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+drop+go9+test --seed 9462 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+go9+test --seed 12351 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+go6+test --seed 18295 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+drop+test --seed 18472 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+go9+test --seed 19248 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+go6+test --seed 22923 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+go9+test --seed 23475 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+go9+test --seed 24895 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+go12+test --seed 25927 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+go12+test --seed 28150 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+go6+test --seed 36171 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+go6+test --seed 38092 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+open+go6+test --seed 38819 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+go6+test --seed 43477 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+go9+test --seed 44049 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+cook+cut+drop+test --seed 46858 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+go6+test --seed 47481 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+cook+cut+drop+test --seed 57469 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+go6+test --seed 60215 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+drop+test --seed 1226 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+go12+test --seed 3245 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+go12+test --seed 3332 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+drop+test --seed 4146 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+open+go12+test --seed 5469 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+go12+test --seed 5790 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+go12+test --seed 6841 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+drop+go12+test --seed 7734 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+go6+test --seed 12135 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+drop+go6+test --seed 12219 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+go6+test --seed 12939 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+drop+test --seed 13796 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+drop+test --seed 14377 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+go9+test --seed 15897 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+go6+test --seed 17093 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+go6+test --seed 17960 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+open+test --seed 18535 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+go6+test --seed 19156 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+drop+go9+test --seed 20407 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+go9+test --seed 21751 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+drop+go6+test --seed 22719 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+go9+test --seed 25515 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+test --seed 27435 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+test --seed 27486 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+test --seed 27864 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+test --seed 27926 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+go12+test --seed 28473 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+go9+test --seed 28583 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+test --seed 30355 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+drop+test --seed 32685 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+open+go6+test --seed 33714 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+go9+test --seed 33715 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+drop+go6+test --seed 34162 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+go12+test --seed 34332 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+open+go6+test --seed 34394 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+test --seed 34541 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+drop+go6+test --seed 34838 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+drop+go9+test --seed 36500 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+go6+test --seed 36996 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+drop+test --seed 37356 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+go12+test --seed 38863 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+go9+test --seed 41153 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+open+go9+test --seed 43184 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+open+go9+test --seed 43725 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+drop+go6+test --seed 44037 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+open+go6+test --seed 47201 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+go6+test --seed 47253 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+go9+test --seed 48934 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+open+test --seed 49649 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+drop+go6+test --seed 50070 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+open+go9+test --seed 51183 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+test --seed 52856 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+open+go6+test --seed 55752 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+open+test --seed 56480 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+drop+go9+test --seed 56756 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+drop+go6+test --seed 58775 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+open+go9+test --seed 60796 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+drop+test --seed 60989 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+go6+test --seed 61010 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+go9+test --seed 61192 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+drop+test --seed 61406 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+go12+test --seed 61875 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+open+test --seed 62092 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+drop+go9+test --seed 62285 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+drop+go9+test --seed 62562 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+go12+test --seed 63644 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+test --seed 63784 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+drop+test --seed 64453 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+go9+test --seed 64470 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+test --seed 11115 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+open+go12+test --seed 14611 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+drop+go12+test --seed 15339 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+drop+test --seed 16897 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+open+drop+test --seed 18636 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+drop+go12+test --seed 20507 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+open+test --seed 23671 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+drop+test --seed 24480 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+open+test --seed 28931 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+go12+test --seed 29322 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+test --seed 33169 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+drop+go12+test --seed 34589 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+open+drop+test --seed 34660 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+drop+test --seed 36294 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+drop+go12+test --seed 41912 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+open+test --seed 42177 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+go12+test --seed 44496 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+drop+test --seed 46641 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+test --seed 47895 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+drop+go12+test --seed 47934 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+open+test --seed 49707 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+go12+test --seed 49893 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+open+go12+test --seed 56420 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+drop+test --seed 56956 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+open+drop+test --seed 60364 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+drop+test --seed 62006 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+go12+test --seed 62055 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+drop+test --seed 62843 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+open+drop+test --seed 63813 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+drop+test --seed 64245 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+open+go12+test --seed 64288 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+drop+go6+test --seed 2405 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+drop+go6+test --seed 6632 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+drop+test --seed 815 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+go9+test --seed 1948 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+open+go6+test --seed 4069 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+go6+test --seed 4404 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+drop+go6+test --seed 6151 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+go9+test --seed 6532 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+drop+go9+test --seed 8415 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+drop+go9+test --seed 29368 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+drop+go9+test --seed 43562 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+go9+test --seed 52035 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+go6+test --seed 63850 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+go12+test --seed 1172 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+open+go6+test --seed 1473 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+go12+test --seed 2123 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+drop+go12+test --seed 2324 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+open+drop+go6+test --seed 2831 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+open+drop+go9+test --seed 3277 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+drop+go12+test --seed 3441 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+drop+test --seed 3681 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+drop+test --seed 4720 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+drop+go12+test --seed 5954 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+open+drop+test --seed 5962 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+open+drop+go9+test --seed 6002 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+go12+test --seed 6292 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+drop+go6+test --seed 7350 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+drop+go9+test --seed 10332 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+go9+test --seed 12796 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+open+go9+test --seed 13057 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+drop+go9+test --seed 13144 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+go9+test --seed 15478 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+drop+go9+test --seed 15660 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+go6+test --seed 16597 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+go9+test --seed 17797 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+drop+go6+test --seed 19036 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+drop+go9+test --seed 23789 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+open+go9+test --seed 24922 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+open+go6+test --seed 28189 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+go6+test --seed 29318 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+drop+go6+test --seed 30484 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+go6+test --seed 31058 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+open+go6+test --seed 31237 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+go12+test --seed 34416 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+drop+go9+test --seed 34444 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+go6+test --seed 34506 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+go9+test --seed 38558 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cut+open+drop+go12+test --seed 39672 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+go6+test --seed 42824 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+go9+test --seed 43399 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+drop+go6+test --seed 44027 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+drop+go6+test --seed 44147 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+go6+test --seed 45309 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+drop+go9+test --seed 46878 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+go9+test --seed 48305 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+go9+test --seed 51139 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+open+go6+test --seed 53719 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+drop+go12+test --seed 56644 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+open+go9+test --seed 58755 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+open+go9+test --seed 59635 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+go6+test --seed 60135 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+go6+test --seed 60251 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+drop+go6+test --seed 60906 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+go9+test --seed 60914 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+go6+test --seed 64352 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+drop+go6+test --seed 64765 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+open+go12+test --seed 1538 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+drop+go12+test --seed 2086 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+open+drop+test --seed 2616 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+open+drop+go12+test --seed 3810 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+open+go12+test --seed 4116 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+open+drop+go12+test --seed 7460 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+drop+go12+test --seed 9255 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+drop+go12+test --seed 9432 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+drop+test --seed 9875 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+test --seed 10200 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+open+go9+test --seed 11773 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+open+go12+test --seed 12960 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+test --seed 13429 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+open+drop+test --seed 13436 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+drop+go9+test --seed 13730 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+open+drop+test --seed 14216 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+open+go9+test --seed 15143 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+drop+go12+test --seed 15490 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+open+drop+go9+test --seed 16423 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+drop+go6+test --seed 17730 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+drop+go6+test --seed 17934 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+open+drop+go6+test --seed 18333 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+drop+test --seed 18391 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+go12+test --seed 18453 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+open+go12+test --seed 18694 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+drop+go6+test --seed 21445 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+go9+test --seed 22107 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+go12+test --seed 25474 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+go9+test --seed 25893 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+drop+test --seed 27380 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+open+go9+test --seed 28469 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+drop+go12+test --seed 30069 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+drop+go9+test --seed 32442 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+open+go6+test --seed 34814 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+open+drop+go6+test --seed 35514 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+go6+test --seed 36541 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+drop+go12+test --seed 36793 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+test --seed 37013 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+go9+test --seed 37573 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+open+go12+test --seed 39272 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+open+test --seed 40360 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+drop+go9+test --seed 41475 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+open+test --seed 41619 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+drop+go6+test --seed 42316 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+open+drop+go6+test --seed 42929 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+drop+go9+test --seed 43887 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+go12+test --seed 44538 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+open+test --seed 45346 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+open+test --seed 45668 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+open+go6+test --seed 46253 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+drop+test --seed 46363 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+drop+go9+test --seed 46376 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+go6+test --seed 46622 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+drop+test --seed 46705 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+open+drop+test --seed 46952 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+drop+go9+test --seed 47041 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+go12+test --seed 47460 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+drop+go9+test --seed 47753 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+drop+test --seed 47947 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+open+go6+test --seed 48560 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+go12+test --seed 51641 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+drop+go6+test --seed 53316 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+drop+go6+test --seed 53867 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+drop+go9+test --seed 53937 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+drop+go9+test --seed 54634 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+drop+go12+test --seed 56183 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+drop+test --seed 56309 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+open+drop+go6+test --seed 57383 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+drop+go6+test --seed 59820 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+go6+test --seed 59983 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+drop+test --seed 61395 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+drop+go6+test --seed 61929 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+go12+test --seed 62903 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+drop+go9+test --seed 63116 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+open+go12+test --seed 63182 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+open+drop+go9+test --seed 63639 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+go12+test --seed 63784 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+open+go9+test --seed 64759 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+open+drop+go12+test --seed 10820 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+drop+go12+test --seed 10976 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+open+go12+test --seed 12582 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+go12+test --seed 13340 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+drop+go12+test --seed 13652 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+open+drop+test --seed 16850 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+open+drop+go12+test --seed 22814 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+drop+go12+test --seed 27018 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+drop+test --seed 27071 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+open+drop+test --seed 31304 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+drop+go12+test --seed 32116 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+drop+test --seed 36763 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+go12+test --seed 37933 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+open+drop+test --seed 45921 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+go12+test --seed 52453 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+drop+go12+test --seed 54453 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+open+drop+go12+test --seed 56558 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+open+go12+test --seed 57075 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+open+drop+go12+test --seed 65320 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+open+drop+go9+test --seed 266 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+open+drop+go9+test --seed 776 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+open+drop+go9+test --seed 891 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+drop+go6+test --seed 8050 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+drop+go9+test --seed 2118 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+drop+go9+test --seed 4731 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+open+drop+go6+test --seed 4830 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+drop+go6+test --seed 5824 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+open+go9+test --seed 6877 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+drop+go9+test --seed 28614 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+open+drop+go6+test --seed 5880 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+go12+test --seed 5892 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+open+drop+go12+test --seed 6244 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+open+go12+test --seed 7024 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+go12+test --seed 8198 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+drop+go9+test --seed 10310 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+drop+go6+test --seed 11901 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+drop+go6+test --seed 13517 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+drop+go6+test --seed 14076 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+go9+test --seed 16908 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+open+drop+go6+test --seed 17083 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+go9+test --seed 17762 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+open+go6+test --seed 19149 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+open+go6+test --seed 23794 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+drop+go6+test --seed 24786 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+open+go9+test --seed 25493 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+drop+go6+test --seed 25893 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+drop+go9+test --seed 26847 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+go6+test --seed 27165 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+drop+go6+test --seed 30741 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+go9+test --seed 33847 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+drop+go6+test --seed 34976 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+drop+go9+test --seed 37616 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+drop+go6+test --seed 38180 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+drop+go6+test --seed 39227 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+drop+go9+test --seed 39547 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cut+open+drop+go6+test --seed 42734 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+open+drop+go9+test --seed 43172 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+go6+test --seed 43569 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+drop+go9+test --seed 44378 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+open+go9+test --seed 45232 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+cook+cut+open+drop+go12+test --seed 45982 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+open+go9+test --seed 46069 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+open+go6+test --seed 46463 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+drop+go9+test --seed 51336 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+open+go6+test --seed 51491 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+drop+go9+test --seed 54685 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+go6+test --seed 55510 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+drop+go9+test --seed 58864 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+open+drop+go6+test --seed 64219 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+open+drop+go12+test --seed 1977 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+open+drop+go12+test --seed 2200 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+open+drop+go9+test --seed 11835 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+open+drop+test --seed 11842 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+open+drop+go9+test --seed 13114 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+drop+test --seed 13958 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+drop+test --seed 15537 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+drop+go6+test --seed 17871 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+open+drop+go9+test --seed 18320 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+drop+go9+test --seed 18612 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+open+go12+test --seed 19696 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+drop+test --seed 20615 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+drop+go12+test --seed 25773 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cut+open+drop+go12+test --seed 26497 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+drop+go9+test --seed 26760 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+drop+go12+test --seed 32779 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+drop+go12+test --seed 32947 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cut+open+drop+go12+test --seed 33000 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+open+drop+test --seed 38198 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+open+go12+test --seed 40386 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+open+drop+go6+test --seed 41386 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+drop+go6+test --seed 42991 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cut+open+drop+go12+test --seed 43300 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cut+open+drop+go12+test --seed 46556 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cut+open+drop+go12+test --seed 48491 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cut+open+drop+go12+test --seed 50655 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+open+drop+go6+test --seed 50985 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+drop+go12+test --seed 51136 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+drop+go9+test --seed 52037 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+open+drop+test --seed 52215 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+open+drop+go6+test --seed 52591 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+drop+go12+test --seed 53157 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+open+go12+test --seed 53829 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+go12+test --seed 54801 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+open+drop+test --seed 57497 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+drop+go12+test --seed 57804 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+open+drop+go9+test --seed 57869 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+drop+go12+test --seed 61573 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+drop+go6+test --seed 63025 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+drop+go6+test --seed 72 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+open+drop+go12+test --seed 15831 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+open+drop+go12+test --seed 20377 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+open+drop+go12+test --seed 30990 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+open+drop+go12+test --seed 31366 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+open+drop+go12+test --seed 38276 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+open+drop+go6+test --seed 766 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+open+drop+go12+test --seed 1573 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+drop+go12+test --seed 2252 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+open+drop+go6+test --seed 12887 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+drop+go9+test --seed 17077 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+open+drop+go9+test --seed 21263 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+open+drop+go9+test --seed 29558 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+open+drop+go9+test --seed 34207 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+drop+go6+test --seed 35205 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take3+cook+cut+open+drop+go6+test --seed 42927 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+open+drop+go9+test --seed 50906 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+open+drop+go6+test --seed 51304 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe3+take3+cook+cut+open+drop+go9+test --seed 53474 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+drop+go6+test --seed 53964 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+drop+go9+test --seed 60136 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take5+cook+cut+open+drop+go12+test --seed 13087 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe5+take4+cook+cut+open+drop+go12+test --seed 31797 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe2+take2+cook+cut+open+drop+go12+test --seed 40656 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe4+take4+cook+cut+open+drop+go12+test --seed 42538 --output $OUTPUT_FOLDER/test/ --silent -f
tw-make challenge tw-cooking-recipe1+take1+cook+cut+open+drop+go12+test --seed 46737 --output $OUTPUT_FOLDER/test/ --silent -f
